"use client";

import React from 'react';
import { FileText, Bot, Mail, Phone, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

const TermsAndConditions: React.FC = () => {
  return (
    <div className="min-h-screen bg-slate-50 pt-32 pb-20">
      <div className="max-w-4xl mx-auto px-6">
        <div className="bg-white rounded-2xl shadow-xl border border-slate-200 p-8 md:p-12">
          
          <Link to="/" className="text-indigo-600 hover:text-indigo-800 text-sm font-medium mb-6 flex items-center gap-1">
            <ArrowLeft className="w-4 h-4" /> Back to Homepage
          </Link>
          
          <h1 className="text-4xl font-bold text-slate-900 mb-4 flex items-center gap-3">
            <FileText className="w-8 h-8 text-indigo-600" /> Terms and Conditions
          </h1>
          <p className="text-slate-500 mb-8">
            Effective Date: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>

          <div className="space-y-8 text-slate-700 leading-relaxed">
            
            <section>
              <h2 className="text-2xl font-bold text-slate-900 mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing and using the website and services of Custom Websites Plus ("CWP"), you agree to be bound by these Terms and Conditions ("Terms"). If you disagree with any part of the terms, you may not access the service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 mb-3">2. Services Provided</h2>
              <p>
                CWP provides custom web design, development, local SEO optimization, and AI integration services for local businesses. All services are subject to a separate, written Service Agreement or Proposal.
              </p>
              <ul className="list-disc list-inside ml-4 space-y-2 mt-3">
                <li><strong>Project Scope:</strong> The scope of work is defined exclusively in the signed proposal. Any work outside this scope requires a change order and may incur additional fees.</li>
                <li><strong>Payment:</strong> Projects typically require an upfront deposit, with remaining payments tied to milestones. Failure to meet payment deadlines may result in project pause or termination.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 mb-3">3. Use of Free Tools (JetSuite)</h2>
              <p>
                Our free tools, including the Jet Local Optimizer and JetViz, are provided "as is" for informational and diagnostic purposes only.
              </p>
              <ul className="list-disc list-inside ml-4 space-y-2 mt-3">
                <li><strong>Accuracy:</strong> We do not guarantee the accuracy of the analysis results, which are based on third-party APIs (Google PageSpeed) and proprietary scanning heuristics.</li>
                <li><strong>AI Content:</strong> Any content generated by our AI tools (e.g., Luna Chat) is for informational purposes only and should not be relied upon as professional advice.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 mb-3">4. Intellectual Property</h2>
              <p>
                Upon final payment for a website rebuild project, the client is granted full ownership and intellectual property rights to the final design and code. CWP retains the right to use the project in its portfolio and marketing materials.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 mb-3">5. Limitation of Liability</h2>
              <p>
                In no event shall CWP, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 mb-3">6. Governing Law</h2>
              <p>
                These Terms shall be governed and construed in accordance with the laws of the State of Georgia, United States, without regard to its conflict of law provisions.
              </p>
            </section>

            <div className="p-4 bg-red-50 border border-red-200 rounded-xl text-sm mt-10">
                <strong>Legal Disclaimer:</strong> This document is provided for informational purposes only and is AI-assisted. It does not constitute legal advice. Please consult with a legal professional to ensure compliance with all applicable laws.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;