import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { GoogleGenAI } from 'https://esm.sh/@google/genai@1.34.0';
import { handleCors, jsonResponse, errorResponse } from '../_shared/utils.ts';

const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY');

if (!GEMINI_API_KEY) {
  throw new Error('GEMINI_API_KEY is not set.');
}

const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

serve(async (req) => {
  const corsResponse = handleCors(req);
  if (corsResponse) return corsResponse;

  try {
    const { documentType, inputs } = await req.json();

    if (!documentType || !inputs) {
      return errorResponse('Missing documentType or inputs.', 400);
    }
    
    console.log(`[generate-document] Generating document type: ${documentType}`);

    const systemInstruction = `You are a professional AI legal drafting assistant. Your goal is to generate a comprehensive, well-structured draft document based on the user's inputs. 
    
    CRITICAL RULES:
    1. DO NOT provide legal advice or guarantee compliance.
    2. Start the document with a clear, bold title (e.g., "TERMS AND CONDITIONS").
    3. Use markdown formatting (headings, lists, bold text) for readability.
    4. Include placeholders (e.g., [Effective Date]) where specific dates or details are missing.
    5. The output must be ONLY the document text, without any conversational preamble or postamble.
    6. The document must be a DRAFT and include a section clearly stating it is AI-generated and requires legal review.
    
    Contextual Inputs: ${JSON.stringify(inputs, null, 2)}`;

    const prompt = `Generate a draft ${documentType} document for a business named "${inputs.clientName}" operating a "${inputs.projectType}" website at "${inputs.websiteUrl}". 
    
    Key details:
    - Contact Email: ${inputs.contactEmail}
    - Jurisdiction: ${inputs.jurisdiction}
    - Services Provided: ${inputs.servicesProvided.join(', ')}
    - Data Collected: ${inputs.dataCollected.join(', ')}
    - Special Notes: ${inputs.specialNotes || 'None'}
    
    Ensure the document covers standard clauses relevant to the document type and the provided inputs.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      config: {
        systemInstruction: systemInstruction,
        temperature: 0.5,
      },
    });

    const generatedContent = response.text;

    // Add the mandatory disclaimer (Step 3)
    const finalContent = `${generatedContent}\n\n---\n\n## AI Drafting Disclaimer\n\n**This document is generated by AI for general informational purposes and does not constitute legal advice.** It is a draft intended to accelerate the drafting process. Please consult a licensed attorney in your jurisdiction to review, customize, and approve this document before publishing or relying on it. Custom Websites Plus and its affiliates are not responsible for any legal consequences resulting from the use of this draft document.`;

    return jsonResponse({ success: true, content: finalContent });

  } catch (error: any) {
    console.error('[generate-document] Unhandled error:', error.message);
    return errorResponse(error.message, 500);
  }
});